# Generated by Django 4.1.5 on 2023-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField(blank=True, null=True)),
                ('Region', models.CharField(default='', max_length=90, null=True)),
                ('City', models.CharField(default='', max_length=90, null=True)),
                ('Catagory', models.CharField(default='', max_length=90, null=True)),
                ('Product', models.CharField(default='', max_length=90, null=True)),
                ('Quantity', models.IntegerField(default=0, null=True)),
                ('UnitPrice', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
